global using System.IdentityModel.Tokens.Jwt;
global using System.Security.Claims;
global using System.Text;
global using Microsoft.Extensions.Configuration;
global using Microsoft.IdentityModel.Tokens;
global using Newtonsoft.Json;
global using QRCoder;
global using StackExchange.Redis;
global using System.Security.Cryptography;
