@KBZLifeInsuranceCodeTest.GiftCardManagementSystem_HostAddress = http://localhost:5115

GET {{KBZLifeInsuranceCodeTest.GiftCardManagementSystem_HostAddress}}/weatherforecast/
Accept: application/json

###
